version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=debbi
      - POSTGRES_USER=debbico
      - POSTGRES_PASSWORD=debbico22
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=hola@debbi.co
      - PGADMIN_DEFAULT_PASSWORD=debbico22
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
    ports:
      - 5051:80
